package com.superlcb.mapper;

import com.superlcb.entity.UserAutoEntity;
import com.superlcb.entity.UserAutoEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAutoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    long countByExample(UserAutoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    int deleteByExample(UserAutoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    int insert(UserAutoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    int insertSelective(UserAutoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    List<UserAutoEntity> selectByExample(UserAutoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    UserAutoEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserAutoEntity record, @Param("example") UserAutoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    int updateByExample(@Param("record") UserAutoEntity record, @Param("example") UserAutoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    int updateByPrimaryKeySelective(UserAutoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    int updateByPrimaryKey(UserAutoEntity record);
}