package com.superlcb.entity;

public class UserAutoEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.id
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    private Integer id;

    @Override
    public String toString() {
        return "UserAutoEntity{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                '}';
    }

    /**
     *
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.userName
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.password
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.id
     *
     * @return the value of myuser.id
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.id
     *
     * @param id the value for myuser.id
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.userName
     *
     * @return the value of myuser.userName
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.userName
     *
     * @param username the value for myuser.userName
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.password
     *
     * @return the value of myuser.password
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.password
     *
     * @param password the value for myuser.password
     *
     * @mbg.generated Mon Jul 22 20:28:04 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }
}